---
default_config:

homeassistant:
  customize: !include customize.yaml

group: !include group.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

influxdb:
  api_version: 2
  host: !secret host
  port: !secret influx_port
  token: !secret influx_token
  organization: !secret influx_organization
  bucket: !secret influx_bucket
  max_retries: 3
  ssl: false

http:
  use_x_forwarded_for: true
  trusted_proxies: !secret trusted_proxies

input_number:
  living_room_top_blinds_slider: &slider
    name: Living Room - Top Blinds Slider
    min: -100
    max: 100
    step: 10
  living_room_bottom_blinds_slider:
    <<: *slider
    name: Living Room - Bottom Blinds Slider
  office_top_blinds_slider:
    <<: *slider
    name: Office - Top Blinds Slider
  office_bottom_blinds_slider:
    <<: *slider
    name: Office - Bottom Blinds Slider
  bedroom_top_blinds_slider:
    <<: *slider
    name: Bedroom - Top Blinds Slider
  bedroom_bottom_blinds_slider:
    <<: *slider
    name: Bedroom - Bottom Blinds Slider
  porch_blinds_slider:
    <<: *slider
    name: Porch - Blinds Slider

## Rest Commands
rest_command:
  sunsa_living_room_top_blinds: &sunsa-rest
    url: !secret api_sunsa_living_room_top_blinds
    method: PUT
    headers:
      accept: "application/json"
    payload: '{"Position": {{ position }}}'
    content_type: "application/json"
  sunsa_living_room_bottom_blinds:
    <<: *sunsa-rest
    url: !secret api_sunsa_living_room_bottom_blinds
  sunsa_office_top_blinds:
    <<: *sunsa-rest
    url: !secret api_sunsa_office_top_blinds
  sunsa_office_bottom_blinds:
    <<: *sunsa-rest
    url: !secret api_sunsa_office_bottom_blinds
  sunsa_bedroom_top_blinds:
    <<: *sunsa-rest
    url: !secret api_sunsa_bedroom_top_blinds
  sunsa_bedroom_bottom_blinds:
    <<: *sunsa-rest
    url: !secret api_sunsa_bedroom_bottom_blinds
  sunsa_porch_blinds:
    <<: *sunsa-rest
    url: !secret api_sunsa_porch_blinds

sensor:
  - platform: rest
    resource: !secret api_sunsa_main
    name: api_sunsa_main
    json_attributes:
      - devices
    value_template: "OK"

  - platform: template
    sensors:
      # Living Room - Top
      living_room_top_blinds_battery_percentage:
        friendly_name: "Living Room - Top Blinds Battery Percentage"
        device_class: battery
        value_template: "{{ state_attr('sensor.api_sunsa_main', 'devices')[3]['batteryPercentage'] }}"
        unit_of_measurement: "%"
        icon_template: mdi:battery-high
      living_room_top_blinds_position:
        friendly_name: "Living Room - Top Blinds Position"
        value_template: "{{ state_attr('sensor.api_sunsa_main', 'devices')[3]['position'] }}"
        unit_of_measurement: "%"
        icon_template: mdi:blinds-horizontal
      living_room_top_blinds_is_connected:
        friendly_name: "Living Room - Top Blinds Connection Status"
        value_template: "{{ state_attr('sensor.api_sunsa_main', 'devices')[3]['isConnected'] }}"
        icon_template: mdi:connection

      # Living Room - Bottom
      living_room_bottom_blinds_battery_percentage:
        friendly_name: "Living Room - Bottom Blinds Battery Percentage"
        device_class: battery
        value_template: "{{ state_attr('sensor.api_sunsa_main', 'devices')[2]['batteryPercentage'] }}"
        unit_of_measurement: "%"
        icon_template: mdi:battery-high
      living_room_bottom_blinds_position:
        friendly_name: "Living Room - Bottom Blinds Position"
        value_template: "{{ state_attr('sensor.api_sunsa_main', 'devices')[2]['position'] }}"
        unit_of_measurement: "%"
        icon_template: mdi:blinds-horizontal
      living_room_bottom_blinds_is_connected:
        friendly_name: "Living Room - Bottom Blinds Connection Status"
        value_template: "{{ state_attr('sensor.api_sunsa_main', 'devices')[2]['isConnected'] }}"
        icon_template: mdi:connection

      # Office - Top
      office_top_blinds_battery_percentage:
        friendly_name: "Office - Top Blinds Battery Percentage"
        device_class: battery
        value_template: "{{ state_attr('sensor.api_sunsa_main', 'devices')[5]['batteryPercentage'] }}"
        unit_of_measurement: "%"
        icon_template: mdi:battery-high
      office_top_blinds_position:
        friendly_name: "Office - Top Blinds Position"
        value_template: "{{ state_attr('sensor.api_sunsa_main', 'devices')[5]['position'] }}"
        unit_of_measurement: "%"
        icon_template: mdi:blinds-horizontal
      office_top_blinds_is_connected:
        friendly_name: "Office - Top Blinds Connection Status"
        value_template: "{{ state_attr('sensor.api_sunsa_main', 'devices')[5]['isConnected'] }}"
        icon_template: mdi:connection

      # Office - Bottom
      office_bottom_blinds_battery_percentage:
        friendly_name: "Office - Bottom Blinds Battery Percentage"
        device_class: battery
        value_template: "{{ state_attr('sensor.api_sunsa_main', 'devices')[4]['batteryPercentage'] }}"
        unit_of_measurement: "%"
        icon_template: mdi:battery-high
      office_bottom_blinds_position:
        friendly_name: "Office - Bottom Blinds Position"
        value_template: "{{ state_attr('sensor.api_sunsa_main', 'devices')[4]['position'] }}"
        unit_of_measurement: "%"
        icon_template: mdi:blinds-horizontal
      office_bottom_blinds_is_connected:
        friendly_name: "Office - Bottom Blinds Connection Status"
        value_template: "{{ state_attr('sensor.api_sunsa_main', 'devices')[4]['isConnected'] }}"
        icon_template: mdi:connection

      # Bedroom - Top
      bedroom_top_blinds_battery_percentage:
        friendly_name: "Bedroom - Top Blinds Battery Percentage"
        device_class: battery
        value_template: "{{ state_attr('sensor.api_sunsa_main', 'devices')[1]['batteryPercentage'] }}"
        unit_of_measurement: "%"
        icon_template: mdi:battery-high
      bedroom_top_blinds_position:
        friendly_name: "Bedroom - Top Blinds Position"
        value_template: "{{ state_attr('sensor.api_sunsa_main', 'devices')[1]['position'] }}"
        unit_of_measurement: "%"
        icon_template: mdi:blinds-horizontal
      bedroom_top_blinds_is_connected:
        friendly_name: "Bedroom - Top Blinds Connection Status"
        value_template: "{{ state_attr('sensor.api_sunsa_main', 'devices')[1]['isConnected'] }}"
        icon_template: mdi:connection

      # Bedroom - Bottom
      bedroom_bottom_blinds_battery_percentage:
        friendly_name: "Bedroom - Bottom Blinds Battery Percentage"
        device_class: battery
        value_template: "{{ state_attr('sensor.api_sunsa_main', 'devices')[0]['batteryPercentage'] }}"
        unit_of_measurement: "%"
        icon_template: mdi:battery-high
      bedroom_bottom_blinds_position:
        friendly_name: "Bedroom - Bottom Blinds Position"
        value_template: "{{ state_attr('sensor.api_sunsa_main', 'devices')[0]['position'] }}"
        unit_of_measurement: "%"
        icon_template: mdi:blinds-horizontal
      bedroom_bottom_blinds_is_connected:
        friendly_name: "Bedroom - Bottom Blinds Connection Status"
        value_template: "{{ state_attr('sensor.api_sunsa_main', 'devices')[0]['isConnected'] }}"
        icon_template: mdi:connection

      # Porch
      porch_blinds_battery_percentage:
        friendly_name: "Porch - Blinds Battery Percentage"
        device_class: battery
        value_template: "{{ state_attr('sensor.api_sunsa_main', 'devices')[6]['batteryPercentage'] }}"
        unit_of_measurement: "%"
        icon_template: mdi:battery-high
      porch_blinds_position:
        friendly_name: "Porch - Blinds Position"
        value_template: "{{ state_attr('sensor.api_sunsa_main', 'devices')[6]['position'] }}"
        unit_of_measurement: "%"
        icon_template: mdi:blinds-horizontal
      porch_blinds_is_connected:
        friendly_name: "Porch - Blinds Connection Status"
        value_template: "{{ state_attr('sensor.api_sunsa_main', 'devices')[6]['isConnected'] }}"
        icon_template: mdi:connection

cover:
  - platform: template
    covers:
      # Living Room - Top Blinds
      living_room_top_blinds:
        unique_id: living_room_top_blinds
        friendly_name: "Living Room - Top Blinds"
        device_class: blind
        open_cover:
          service: rest_command.sunsa_living_room_top_blinds
          data:
            position: "-100"
        stop_cover:
          service: rest_command.sunsa_living_room_top_blinds
          data:
            position: "0"
        close_cover:
          service: rest_command.sunsa_living_room_top_blinds
          data:
            position: "100"

      living_room_bottom_blinds:
        unique_id: living_room_bottom_blinds
        friendly_name: "Living Room - Bottom Blinds"
        device_class: blind
        open_cover:
          service: rest_command.sunsa_living_room_bottom_blinds
          data:
            position: "-100"
        stop_cover:
          service: rest_command.sunsa_living_room_bottom_blinds
          data:
            position: "0"
        close_cover:
          service: rest_command.sunsa_living_room_bottom_blinds
          data:
            position: "100"

      office_top_blinds:
        unique_id: office_top_blinds
        friendly_name: "Office - Top Blinds"
        device_class: blind
        open_cover:
          service: rest_command.sunsa_office_top_blinds
          data:
            position: "-100"
        stop_cover:
          service: rest_command.sunsa_office_top_blinds
          data:
            position: "0"
        close_cover:
          service: rest_command.sunsa_office_top_blinds
          data:
            position: "100"

      office_bottom_blinds:
        unique_id: office_bottom_blinds
        friendly_name: "Office - Bottom Blinds"
        device_class: blind
        open_cover:
          service: rest_command.sunsa_office_bottom_blinds
          data:
            position: "-100"
        stop_cover:
          service: rest_command.sunsa_office_bottom_blinds
          data:
            position: "0"
        close_cover:
          service: rest_command.sunsa_office_bottom_blinds
          data:
            position: "100"

      bedroom_top_blinds:
        unique_id: bedroom_top_blinds
        friendly_name: "Bedroom - Top Blinds"
        device_class: blind
        open_cover:
          service: rest_command.sunsa_bedroom_top_blinds
          data:
            position: "-100"
        stop_cover:
          service: rest_command.sunsa_bedroom_top_blinds
          data:
            position: "0"
        close_cover:
          service: rest_command.sunsa_bedroom_top_blinds
          data:
            position: "100"

      bedroom_bottom_blinds:
        unique_id: bedroom_bottom_blinds
        friendly_name: "Bedroom - Bottom Blinds"
        device_class: blind
        open_cover:
          service: rest_command.sunsa_bedroom_bottom_blinds
          data:
            position: "-100"
        stop_cover:
          service: rest_command.sunsa_bedroom_bottom_blinds
          data:
            position: "0"
        close_cover:
          service: rest_command.sunsa_bedroom_bottom_blinds
          data:
            position: "100"

      porch_blinds:
        unique_id: porch_blinds
        friendly_name: "Porch - Blinds"
        device_class: blind
        open_cover:
          service: rest_command.sunsa_porch_blinds
          data:
            position: "-100"
        stop_cover:
          service: rest_command.sunsa_porch_blinds
          data:
            position: "0"
        close_cover:
          service: rest_command.sunsa_porch_blinds
          data:
            position: "100"
