---
default_config:

homeassistant:
  customize: !include customize.yaml

group: !include group.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

influxdb:
  api_version: 2
  host: !secret host
  port: !secret influx_port
  token: !secret influx_token
  organization: !secret influx_organization
  bucket: !secret influx_bucket
  max_retries: 3
  ssl: false

http:
  use_x_forwarded_for: true
  trusted_proxies: !secret trusted_proxies
