---
id: '1674335509351'
alias: Living Room Light Switch
description: ''
trigger:
- platform: device
  device_id: 797a79836dddf66e708ed9bf707bb4d6
  domain: zwave_js
  type: event.value_notification.central_scene
  property: scene
  property_key: '001'
  endpoint: 0
  command_class: 91
  subtype: Endpoint 0 Scene 001
  value: 0
  id: TopPressed
- platform: device
  device_id: 797a79836dddf66e708ed9bf707bb4d6
  domain: zwave_js
  type: event.value_notification.central_scene
  property: scene
  property_key: '002'
  endpoint: 0
  command_class: 91
  subtype: Endpoint 0 Scene 002
  value: 1
  id: TopReleased
- platform: device
  device_id: 797a79836dddf66e708ed9bf707bb4d6
  domain: zwave_js
  type: event.value_notification.central_scene
  property: scene
  property_key: '001'
  endpoint: 0
  command_class: 91
  subtype: Endpoint 0 Scene 001
  value: 2
  id: TopHeld
- platform: device
  device_id: 797a79836dddf66e708ed9bf707bb4d6
  domain: zwave_js
  type: event.value_notification.central_scene
  property: scene
  property_key: '001'
  endpoint: 0
  command_class: 91
  subtype: Endpoint 0 Scene 001
  value: 3
  id: TopPressed2
- platform: device
  device_id: 797a79836dddf66e708ed9bf707bb4d6
  domain: zwave_js
  type: event.value_notification.central_scene
  property: scene
  property_key: '001'
  endpoint: 0
  command_class: 91
  subtype: Endpoint 0 Scene 001
  value: 4
  id: TopPressed3
- platform: device
  device_id: 797a79836dddf66e708ed9bf707bb4d6
  domain: zwave_js
  type: event.value_notification.central_scene
  property: scene
  property_key: '001'
  endpoint: 0
  command_class: 91
  subtype: Endpoint 0 Scene 001
  value: 5
  id: TopPressed4
- platform: device
  device_id: 797a79836dddf66e708ed9bf707bb4d6
  domain: zwave_js
  type: event.value_notification.central_scene
  property: scene
  property_key: '001'
  endpoint: 0
  command_class: 91
  subtype: Endpoint 0 Scene 001
  value: 6
  id: TopPressed5
- platform: device
  device_id: 797a79836dddf66e708ed9bf707bb4d6
  domain: zwave_js
  type: event.value_notification.central_scene
  property: scene
  property_key: '002'
  endpoint: 0
  command_class: 91
  subtype: Endpoint 0 Scene 002
  value: 0
  id: BottomPressed
- platform: device
  device_id: 797a79836dddf66e708ed9bf707bb4d6
  domain: zwave_js
  type: event.value_notification.central_scene
  property: scene
  property_key: '002'
  endpoint: 0
  command_class: 91
  subtype: Endpoint 0 Scene 002
  value: 1
  id: BottomReleased
- platform: device
  device_id: 797a79836dddf66e708ed9bf707bb4d6
  domain: zwave_js
  type: event.value_notification.central_scene
  property: scene
  property_key: '002'
  endpoint: 0
  command_class: 91
  subtype: Endpoint 0 Scene 002
  value: 2
  id: BottomHeld
- platform: device
  device_id: 797a79836dddf66e708ed9bf707bb4d6
  domain: zwave_js
  type: event.value_notification.central_scene
  property: scene
  property_key: '002'
  endpoint: 0
  command_class: 91
  subtype: Endpoint 0 Scene 002
  value: 3
  id: BottomPressed2
- platform: device
  device_id: 797a79836dddf66e708ed9bf707bb4d6
  domain: zwave_js
  type: event.value_notification.central_scene
  property: scene
  property_key: '002'
  endpoint: 0
  command_class: 91
  subtype: Endpoint 0 Scene 002
  value: 4
  id: BottomPressed3
- platform: device
  device_id: 797a79836dddf66e708ed9bf707bb4d6
  domain: zwave_js
  type: event.value_notification.central_scene
  property: scene
  property_key: '002'
  endpoint: 0
  command_class: 91
  subtype: Endpoint 0 Scene 002
  value: 5
  id: BottomPressed4
- platform: device
  device_id: 797a79836dddf66e708ed9bf707bb4d6
  domain: zwave_js
  type: event.value_notification.central_scene
  property: scene
  property_key: '002'
  endpoint: 0
  command_class: 91
  subtype: Endpoint 0 Scene 002
  value: 6
  id: BottomPressed5
condition: []
action:
- choose:
  - conditions:
    - condition: trigger
      id: TopPressed
    sequence:
    - service: light.turn_on
      data:
        brightness_pct: 100
      target:
        device_id:
        - 7f6ee59c29c4e1fdeaf8b0ee005df543
        - 23e6092859a3c851d792fd54b98a117f
        - 870eba645fdfef95a789a63a8ced4db5
  - conditions:
    - condition: trigger
      id: TopReleased
    sequence: []
  - conditions:
    - condition: trigger
      id: TopHeld
    sequence:
    - repeat:
        while:
        - condition: trigger
          id: TopHeld
        sequence:
        - device_id: 7f6ee59c29c4e1fdeaf8b0ee005df543
          domain: light
          entity_id: light.living_room_left
          type: brightness_increase
        - device_id: 870eba645fdfef95a789a63a8ced4db5
          domain: light
          entity_id: light.kitchen_left
          type: brightness_increase
        - device_id: 23e6092859a3c851d792fd54b98a117f
          domain: light
          entity_id: light.kitchen_right
          type: brightness_increase
        - delay:
            hours: 0
            minutes: 0
            seconds: 0
            milliseconds: 50
  - conditions:
    - condition: trigger
      id: TopPressed2
    sequence:
    - service: cover.open_cover
      data: {}
      target:
        device_id:
        - 024c1b59d9891d9d95f5ed403eb631c1
        - 452d675feae6b57f9e616055be3bc2ec
        - e4ea1273cd4fada33eae180ce85b22ad
  - conditions:
    - condition: trigger
      id: TopPressed3
    sequence: []
  - conditions:
    - condition: trigger
      id: TopPressed4
    sequence: []
  - conditions:
    - condition: trigger
      id: TopPressed5
    sequence: []
  - conditions:
    - condition: trigger
      id: BottomPressed
    sequence:
    - service: light.turn_off
      data: {}
      target:
        device_id:
        - 7f6ee59c29c4e1fdeaf8b0ee005df543
        - 23e6092859a3c851d792fd54b98a117f
        - 870eba645fdfef95a789a63a8ced4db5
  - conditions:
    - condition: trigger
      id: BottomReleased
    sequence: []
  - conditions:
    - condition: trigger
      id: BottomHeld
    sequence:
    - repeat:
        while:
        - condition: trigger
          id: BottomHeld
        sequence:
        - device_id: 7f6ee59c29c4e1fdeaf8b0ee005df543
          domain: light
          entity_id: light.living_room_left
          type: brightness_decrease
        - device_id: 870eba645fdfef95a789a63a8ced4db5
          domain: light
          entity_id: light.kitchen_left
          type: brightness_decrease
        - device_id: 23e6092859a3c851d792fd54b98a117f
          domain: light
          entity_id: light.kitchen_right
          type: brightness_decrease
        - delay:
            hours: 0
            minutes: 0
            seconds: 0
            milliseconds: 50
  - conditions:
    - condition: trigger
      id: BottomPressed2
    sequence:
    - service: cover.close_cover
      data: {}
      target:
        device_id:
        - 452d675feae6b57f9e616055be3bc2ec
        - 024c1b59d9891d9d95f5ed403eb631c1
        - e4ea1273cd4fada33eae180ce85b22ad
  - conditions:
    - condition: trigger
      id: BottomPressed3
    sequence: []
  - conditions:
    - condition: trigger
      id: BottomPressed4
    sequence: []
  - conditions:
    - condition: trigger
      id: BottomPressed5
    sequence: []
mode: restart
