---
id: "1658629975695"
alias: Movie Playing
description: ""
trigger:
  - platform: template
    value_template: "{{ is_state('media_player.living_room_tv', 'playing') and
      state_attr('media_player.living_room_2', 'app_id') in ['com.disney.disneyplus',
      'com.plexapp.plex', 'com.amazon.aiv.AIVApp'] }} "
condition: []
action:
  - service: scene.create
    data:
      scene_id: before_movie
      snapshot_entities:
        - light.kitchen_left
        - light.kitchen_right
        - light.living_room_floor
        - light.living_room_left
  - service: scene.turn_on
    data:
      transition: 3
    target:
      entity_id: scene.movie
  - wait_for_trigger:
      - platform: state
        entity_id:
          - media_player.living_room_2
        from: playing
    continue_on_timeout: false
  - service: scene.turn_on
    data:
      transition: 3
    target:
      entity_id: scene.before_movie
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - if:
      - condition: template
        value_template:
          "{{ state_attr('sun.sun', 'elevation') < float(states('input_number.sun_elevation_trigger'))
          }}"
    then:
      - service: scene.turn_on
        target:
          entity_id: scene.sundown_diff
        metadata: {}
    else:
      - service: scene.turn_on
        target:
          entity_id: scene.daylight
        metadata: {}
mode: single
