---
id: '1658632765311'
alias: Sundown
description: ''
trigger:
- platform: template
  value_template: '{{ state_attr(''sun.sun'', ''elevation'') < float(states(''input_number.sun_elevation_trigger''))
    }}'
condition:
- condition: state
  entity_id: input_boolean.home
  state: 'on'
action:
- service: scene.turn_on
  target:
    entity_id: scene.sundown_diff
  data: {}
mode: single
